# fly.toml app configuration file generated for netsuite-errors on 2026-04-29T14:58:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'netsuite-errors'
primary_region = 'gru'

[build]
  dockerfile = 'backend/Dockerfile'
  ignorefile = 'backend/.dockerignore'

[env]
  PORT = '3001'

[[services]]
  protocol = 'tcp'
  internal_port = 3001
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '120s'

  [[services.http_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '120s'
    path = '/health'

[checks]
  [checks.status]
    port = 3001
    type = 'http'
    interval = '30s'
    timeout = '10s'
    grace_period = '120s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
